version: '3.8'

services:
  go-backend:
    build: .
    container_name: go-backend
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"